name: Dev Workflows  # Workflows name
on:                  # 언제 실행될 건 설정 (push 되었을 때로 설정)
  push:
    branches:        # brach 설정
      - main         # main 사용
jobs:
  dev-job-first:
    name: dev-job-first      # job name 설정
    runs-on: ubuntu-latest   # 어떤 기반을 사용할지 설정
    steps:                   # steps 설정
    - name: step 1
      run: |
            echo "job 1 / step 1 start time"
            date +"%Y-%m-%d %H:%M:%S.%N"
    - name: step 2
      run: |
            echo "job2 / step 2 start time"
            date +"%Y-%m-%d %H:%M:%S.%N"
            
  dev-job-second:
    name: dev-job-second    
    runs-on: ubuntu-latest   
    steps:                 
    - name: step 1
      run: |
            echo "job 1 / step 1 start time"
            date +"%Y-%m-%d %H:%M:%S.%N"
    - name: step 2
      run: |
            echo "job2 / step 2 start time"
            date +"%Y-%m-%d %H:%M:%S.%N"
