name: Dev Workflows  # Workflows name
on:                  # 언제 실행될 건 설정 (push 되었을 때로 설정)
  push:
    branches:        # brach 설정
      - main         # main 사용
jobs:
  dev-job-first:
    name: dev-job-first      # job name 설정
    runs-on: ubuntu-latest   # 어떤 기반을 사용할지 설정
    steps:                   # steps 설정
    - name: Create a dev.txt
      run: echo "dev file" > dev.txt
    - uses: actions/upload-artifact@v4
      with:
        name: dev-artifact
        path: ./dev.txt
